version: '3.7'

services:
    api:
        build:  
            context: ./app
            dockerfile: Dockerfile.prod
        command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
        volumes:
          - static_volume:/home/app/api/api/staticfiles
          - media_volume:/home/app/api/api/mediafiles
        expose:
            - 8000
        env_file:
            - ./.env
        depends_on:
            - db
            # - broker
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
          - 5432:5432
        env_file:
          - ./.env
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/api/staticfiles
            - media_volume:/home/app/api/api/mediafiles
        ports:
            - 1337:80
        depends_on:
            - api
    # broker:
    #     image: rabbitmq:3-management-alpine
    #     container_name: 'rabbitqm_cotizate'
    #     # env_file:
    #     #   - ./.env
    #     environment:
    #        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
    #        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    #        - CELERY_BROKER=${CELERY_BROKER}
    #        - FLOWER_BROKER=${FLOWER_BROKER}
    #     ports:
    #         - 5672:5672
    #         - 15672:15672
    #     volumes:
    #       - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #       - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    #     networks:
    #       - rabbitmq_net_cotizate
    # worker:
    #     build: ./app
    #     restart: 'no'
    #     # env_file:
    #     #   - ./.env
    #     environment:
    #        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
    #        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    #        - CELERY_BROKER=${CELERY_BROKER}
    #        - FLOWER_BROKER=${FLOWER_BROKER}
    #     command: celery -A api.celery worker -l INFO 
    #     volumes:
    #         - ./app/:/usr/src/app/
    #     depends_on:
    #         - broker
    # flower:
    #     image: zoomeranalytics/flower:0.9.1-4.0.2
    #     restart: 'no'
    #     # env_file:
    #     #   - ./.env
    #     environment:
    #        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
    #        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    #        - CELERY_BROKER=${CELERY_BROKER}
    #        - FLOWER_BROKER=${FLOWER_BROKER}
    #     ports:
    #         - 5555:5555
    #     depends_on:
    #         - broker

volumes:
    postgres_data:
    static_volume:
    media_volume:

# networks:
#   rabbitmq_net_cotizate:
#     driver: bridge
