# Generated by Django 3.2.6 on 2022-07-13 23:42

import autoslug.fields
import core.campaing
import core.profile
import core.profileCompany
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('type_user', models.PositiveSmallIntegerField(choices=[(1, 'contributor'), (2, 'creator')], default=1)),
                ('deleted', models.BooleanField(default=False)),
                ('is_activate', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campaing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_main', models.CharField(blank=True, max_length=250, null=True)),
                ('imagen_main', models.ImageField(upload_to=core.campaing.nameFile)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title')),
                ('excerpt', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('public_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'created'), (2, 'revised'), (3, 'acepted'), (4, 'public'), (5, 'completed'), (6, 'terminated'), (7, 'archived'), (8, 'deleted')], default=2)),
                ('flag', models.PositiveSmallIntegerField(choices=[(1, 'recent'), (2, 'featured'), (3, 'finished')], default=1)),
                ('short_url', models.CharField(blank=True, max_length=100, null=True)),
                ('slogan_campaing', models.CharField(blank=True, max_length=200, null=True)),
                ('qty_day', models.IntegerField(default=0)),
                ('qty_day_left', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_reached', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percent_reached', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('role', models.IntegerField(choices=[(1, 'social cause'), (2, 'entrepreneuship')], default=2)),
                ('code_campaing', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name')),
                ('description', models.CharField(max_length=500)),
                ('img_banner', models.ImageField(blank=True, null=True, upload_to='images/category/banners/')),
                ('img_icon', models.ImageField(blank=True, null=True, upload_to='images/category/icons/')),
                ('delete', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('code_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('code_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Boliviano', max_length=20)),
                ('symbol', models.CharField(default='$BS', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=940)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('delete', models.BooleanField(default=False)),
                ('campaing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaing')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_delivery', models.DateTimeField()),
                ('city', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('all_cities', models.BooleanField(default=False)),
                ('pick_up_locally', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('campaing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaing')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phase')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinit', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=250)),
                ('number_address', models.CharField(max_length=10)),
                ('neightbordhood', models.CharField(blank=True, max_length=250)),
                ('cellphone', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('rs_facebook', models.CharField(blank=True, max_length=350, null=True)),
                ('rs_twitter', models.CharField(blank=True, max_length=350, null=True)),
                ('rs_linkedin', models.CharField(blank=True, max_length=350, null=True)),
                ('rs_another', models.CharField(blank=True, max_length=350, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('representative', models.BooleanField(default=False)),
                ('heading', models.CharField(blank=True, max_length=50, null=True)),
                ('email_company', models.EmailField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.profileCompany.nameFile)),
                ('institution_type', models.PositiveSmallIntegerField(choices=[(1, 'COMPANY'), (2, 'ASSOCIATION'), (3, 'ANOTHER')], default=1)),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinit', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=250)),
                ('number_address', models.CharField(max_length=10)),
                ('neightbordhood', models.CharField(blank=True, max_length=250)),
                ('cellphone', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('rs_facebook', models.CharField(blank=True, max_length=350, null=True)),
                ('rs_twitter', models.CharField(blank=True, max_length=350, null=True)),
                ('rs_linkedin', models.CharField(blank=True, max_length=350, null=True)),
                ('rs_another', models.CharField(blank=True, max_length=350, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('current_position', models.CharField(blank=True, max_length=50, null=True)),
                ('headline', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.profile.nameFile)),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('campaing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='countries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
        migrations.AddField(
            model_name='campaing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='campaing',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
        migrations.AddField(
            model_name='campaing',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency'),
        ),
        migrations.AddField(
            model_name='campaing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked', models.BooleanField(default=False)),
                ('campaing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
