# Generated by Django 3.1.1 on 2020-09-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='campaings',
            field=models.IntegerField(default=0),
        ),
    ]
