# Generated by Django 3.2.6 on 2022-07-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileassociation',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilecompany',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
