# Generated by Django 3.1.7 on 2021-03-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
