# Generated by Django 3.1.2 on 2020-11-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imagen',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
