# Generated by Django 3.1.2 on 2020-11-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaingbody',
            name='imagen_main',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileassociation',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecompany',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
