# Generated by Django 3.2.6 on 2022-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaing',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'created'), (2, 'revised'), (3, 'acepted'), (4, 'public'), (5, 'completed'), (6, 'terminated'), (7, 'archived')], default=2),
        ),
    ]
