# Generated by Django 3.0.9 on 2020-08-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.IntegerField(default=0)),
                ('campaings', models.IntegerField(default=0)),
                ('liked', models.BooleanField(default=False)),
            ],
        ),
    ]
