# Generated by Django 3.2.6 on 2022-07-04 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220704_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecompany',
            name='profiles',
        ),
        migrations.AddField(
            model_name='profilecompany',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
