# Generated by Django 3.1.4 on 2020-12-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_banner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='img_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='img_banner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='img_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
