# Generated by Django 3.1.2 on 2020-11-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201102_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='rs_another',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='rs_facebook',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='rs_linkedin',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='rs_twitter',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='profileassociation',
            name='rs_another',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='profileassociation',
            name='rs_facebook',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='profileassociation',
            name='rs_linkedin',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='profileassociation',
            name='rs_twitter',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='profilecompany',
            name='rs_another',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='profilecompany',
            name='rs_facebook',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='profilecompany',
            name='rs_linkedin',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='profilecompany',
            name='rs_twitter',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
