# Generated by Django 3.2.6 on 2022-07-26 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220723_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('type_pay', models.CharField(blank=True, max_length=100)),
                ('status_pay', models.IntegerField(choices=[(1, 'pending/in-process'), (2, 'paid'), (3, 'reversed'), (4, 'canceled')], default=1)),
                ('coin', models.IntegerField(choices=[(1, 'USD'), (2, 'BOB')], default=2)),
                ('transaction', models.CharField(blank=True, max_length=350)),
                ('campaing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaing')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
