# Generated by Django 3.1.2 on 2020-10-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200928_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaingheader',
            name='code_campaing',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
