# Generated by Django 3.1.7 on 2021-03-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210314_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaingheader',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='campaingheader',
            name='amount_reached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='campaingheader',
            name='percent_reached',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
