# Generated by Django 3.1.2 on 2020-11-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201109_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileassociation',
            name='association_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
