# Generated by Django 3.2.6 on 2022-07-05 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220704_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworkpa',
            name='snet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profilecompany'),
        ),
        migrations.DeleteModel(
            name='ProfileAssociation',
        ),
    ]
