# Generated by Django 3.0.9 on 2020-08-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaing',
            name='short_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
