# Generated by Django 3.1.2 on 2020-11-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201109_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='photo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
