# Generated by Django 3.1.2 on 2020-10-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campaingheader_code_campaing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='description',
            field=models.CharField(max_length=940),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.CharField(max_length=940),
        ),
    ]
