# Generated by Django 3.2.3 on 2021-05-22 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210522_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenouncePublic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=255)),
                ('description', models.CharField(max_length=600)),
                ('campaings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaingheader')),
                ('denouncetxt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.denouncetext')),
            ],
        ),
    ]
