# Generated by Django 3.2 on 2021-04-26 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_updating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenounceText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Denounce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=500)),
                ('campaings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaingheader')),
                ('denouncetxt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.denouncetext')),
            ],
        ),
    ]
