# Generated by Django 3.1.4 on 2020-12-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaingbody_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='campaingbody',
            name='imagen_main',
            field=models.ImageField(upload_to='campaings/'),
        ),
    ]
