# Generated by Django 3.1.2 on 2020-11-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201114_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaingbody',
            name='imagen_main',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profileassociation',
            name='photo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profilecompany',
            name='photo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
