# Generated by Django 3.2.6 on 2022-07-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220705_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecompany',
            name='association_name',
        ),
        migrations.RemoveField(
            model_name='profilecompany',
            name='header',
        ),
        migrations.RemoveField(
            model_name='profilecompany',
            name='representative_name',
        ),
    ]
