# Generated by Django 3.0.9 on 2020-08-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaing_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaing',
            name='short_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
