# Generated by Django 3.1.2 on 2020-10-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201022_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='cities',
            field=models.ManyToManyField(blank=True, to='core.City'),
        ),
    ]
