# Generated by Django 3.1.4 on 2021-01-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201227_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaingbody',
            name='imagen_main',
            field=models.ImageField(blank=True, null=True, upload_to='campaings/'),
        ),
    ]
