# Generated by Django 3.1.2 on 2020-11-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201114_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecompany',
            name='institution_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'COMPANY'), (2, 'ASSOCIATION'), (3, 'ANOTHER')], default=1),
        ),
    ]
