# Generated by Django 3.1.4 on 2021-01-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210102_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaingbody',
            name='imagen_main',
            field=models.ImageField(null=True, upload_to='campaings/'),
        ),
    ]
