# Generated by Django 3.1.4 on 2021-01-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210104_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaingbody',
            name='imagen_main',
            field=models.ImageField(blank=True, null=True, upload_to='campaings/'),
        ),
    ]
