# Generated by Django 3.1.4 on 2021-01-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210104_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img_icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='profileassociation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='associations/'),
        ),
        migrations.AlterField(
            model_name='profilecompany',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='tag',
            name='img_banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='img_icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
