# Generated by Django 3.1.4 on 2021-01-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210120_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='campaing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilecompany',
            name='campaing',
            field=models.IntegerField(default=0),
        ),
    ]
