# Generated by Django 3.1.4 on 2021-01-24 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210124_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalprofile',
            old_name='campaing',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='profilecompany',
            old_name='campaing',
            new_name='header',
        ),
    ]
