# Generated by Django 3.1.4 on 2021-01-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210124_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaingbody',
            name='imagen_main',
        ),
        migrations.AddField(
            model_name='campaingbody',
            name='imagenMain',
            field=models.FileField(blank=True, db_column='imagen_main', null=True, upload_to='campaings/'),
        ),
    ]
