# Generated by Django 3.1.4 on 2021-01-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210129_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaingbody',
            name='imagenMain',
        ),
        migrations.AddField(
            model_name='campaingbody',
            name='imagen_main',
            field=models.ImageField(blank=True, null=True, upload_to='campaings/'),
        ),
    ]
