# Generated by Django 3.1.6 on 2021-02-11 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210129_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='campaings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.campaingheader'),
            preserve_default=False,
        ),
    ]
