# Generated by Django 3.1.6 on 2021-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tag_campaings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaingbody',
            name='imagen_main',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='img_banner',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='img_icon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='photo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profileassociation',
            name='photo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profilecompany',
            name='photo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='img_banner',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='img_icon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
