# Generated by Django 3.1.6 on 2021-02-14 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210214_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('campaings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaingheader')),
            ],
        ),
    ]
